### ISSUE TITLE
怎么部署起来全是错误呢

### ISSUE THREAD

**Issue by dengshaobo** [Lengxiaobing/kettle#1]
怎么项目部署起来全是错误呢，很多类没有提交么，都是缺少方法

**Comment by dengshaobo** [comment]
@Lengxiaobing

**Comment by zhux-dev** [comment]
> 怎么项目部署起来全是错误呢，很多类没有提交么，都是缺少方法
你可以参考readme里面的连接地址，那个是原版，我这个是在那个基础上做了些调整，代码是可以运行的，应该是你依赖有缺失

**Comment by dengshaobo** [comment]
能加您个QQ么 原版我看了，存在很多问题，自己也想用这块，想跟您学习学习，如果方便您加我下QQ吧 953884102

**Comment by dengshaobo** [comment]
> > 怎么项目部署起来全是错误呢，很多类没有提交么，都是缺少方法
> > 你可以参考readme里面的连接地址，那个是原版，我这个是在那个基础上做了些调整，代码是可以运行的，应该是你依赖有缺失
不是依赖的问题，看到都是您新加的类里面的方法，确实没有，不知道是不是没有commit
能加您个QQ么 原版我看了，存在很多问题，自己也想用这块，想跟您学习学习，如果方便您加我下QQ吧 953884102
